### PR TITLE
Skip asking github for latest hash, if we're requesting a specific hash

### PR DESCRIPTION
**Pull request by lurch**
Means one less call to curl in that scenario

### CODE REVIEW

**Comment by popcornmix** [comment]
I wonder if any of this is needed.
I believe ``rpi-update`` and ``rpi-update HEAD`` both get the latest code, so just the line
``FW_REV=${FW_REV:-HEAD}`` may be all that is needed.

**Comment by lurch** [comment]
> just the line FW_REV=${FW_REV:-HEAD} may be all that is needed.

That would end up writing `HEAD` into `/boot/.firmware_revision` though, which probably isn't very useful ;-)

(and I guess https://github.com/Hexxeh/rpi-update/blob/master/rpi-update#L355 means that you'd then only be able to rpi-update just the once?)

**Comment by popcornmix** [comment]
Yes, good point.

**Comment by Ruffio** [comment]
@lurch what is the conclusion on this one? That the RP is ready to merge, that it should be dismissed or?

**Comment by lurch** [comment]
IMHO this patch is still worth merging. I've just rebased it on top of the latest version of master.

**Pull request merged**
