### PR TITLE
Check for NOOBS files in /boot

### PR DESCRIPTION
**Pull request by XECDesign**

### CODE REVIEW

**Comment by popcornmix** [comment]
As this code is temporary, I'd prefer it was moved into a single separate function. Then it's clearer what needs removing in the future.

**Comment by XECDesign** [comment]
updated

**Comment by XECDesign** [comment]
Updated both PRs. I haven't squashed them yet, so that the changes are a bit clearer.

**Comment by popcornmix** [comment]
Both look okay. If you squash, I should be able to merge.

**Comment by XECDesign** [comment]
done

**Pull request merged**
