### PR TITLE
Added expert option section to README.md regarding popcorn mix #197 enhancement

### PR DESCRIPTION
**Pull request by shaun10**
README updates for enhancement related to issue. #197 and commit c2e66a8f7f48d8ec9645c1e44e3a4393e8d6bd2d

### CODE REVIEW

**Comment by popcornmix** [comment]
PRUNE_MODULES is just a boolean. Set it to a non-zero value (1 is the expected choice) and it will remove all modules except the newly installed one.

**Comment by shaun10** [comment]
OK

**Comment by shaun10** [comment]
README has been updated. Thanks again for adding feature popcornmix.

**Comment by popcornmix** [comment]
Can you squash the commits together (``git rebase -i HEAD~2``) and force push?

**Comment by shaun10** [comment]
Sure. I've squashed it into one commit and pushed to the PR.

**Comment by popcornmix** [comment]
Thanks.

**Comment by shaun10** [comment]
Np thanks for feedback.

**Pull request merged**
