### PR TITLE
#220 feature `SKIP_FIRMWARE`

### PR DESCRIPTION
**Pull request by jpluimers**
Feature `SKIP_FIRMWARE` for #220: forces `SKIP_KERNEL=1` and also skip the `kernel.img` files and the kernel modules: This effectively only installs the userland and SDK.

### CODE REVIEW

**Comment by popcornmix** [comment]
Personally I think it would make more sense to make ``SKIP_FIRMWARE`` and ``SKIP_KERNEL`` independent.
SKIP_FIRMWARE would avoid installing ``bootcode.bin``/``start*.elf``/``fixup*.dat``
SKIP_KERNEL would avoid installing ``kernel*.img`` and ``/lib/modules``
For consistency a ``SKIP_USERLAND`` for the ``/opt/vc`` stuff may be useful.

**Comment by popcornmix** [comment]
And yes, supressing the reboot message when ``SKIP_FIRMWARE`` and ``SKIP_KERNEL`` are both enabled.

**Comment by jpluimers** [comment]
I'll see what I can do later this week. Thanks for the remarks.

**Comment by jpluimers** [comment]
Sorry I didn't get to this yet: it's been hectic around here. Will retry after conference season is over (about halfway November)

**Comment by Ruffio** [comment]
@jpluimers Would you update this PR?

**Comment by Ruffio** [comment]
@jpluimers Would you update this PR?

**Comment by Ruffio** [comment]
Is this PR still relevant? If not it should be rejected...

**Comment by popcornmix** [comment]
I'll close - can be reopened if author wants to update it.

**Pull request closed without merging**
